# Generated by Django 4.2.7 on 2023-11-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_id_страницы'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='Id страницы',
        ),
    ]
