# Generated by Django 4.2.7 on 2023-12-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_map_flagforinternalrecordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='FlagForThePresenceOfAParent',
            field=models.IntegerField(default=0, verbose_name='Флаг на наличие родителя'),
        ),
    ]
