# Generated by Django 4.2.7 on 2023-12-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_map_flagforinternalrecordings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='FlagForInternalRecordings',
            field=models.IntegerField(default=0, verbose_name='Флаг на наличие внутренних записей'),
        ),
    ]
