# Generated by Django 4.2.7 on 2024-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_map_nameofpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='countOfVW',
            field=models.IntegerField(default=0, verbose_name='Количество миров '),
        ),
    ]
