# Generated by Django 4.2.7 on 2024-03-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_map_countofvw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='FlagForThePresenceOfAParent',
            field=models.IntegerField(verbose_name='Флаг наличия родительской категории'),
        ),
        migrations.AlterField(
            model_name='map',
            name='countOfVW',
            field=models.IntegerField(default=0, verbose_name='Количество миров'),
        ),
    ]
