# Generated by Django 4.2.15 on 2024-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_map_parent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
