# Generated by Django 4.2.15 on 2024-08-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='FlagForInternalRecordings',
            field=models.BooleanField(default=False, verbose_name='Есть подкатегории'),
        ),
        migrations.AlterField(
            model_name='map',
            name='FlagForThePresenceOfAParent',
            field=models.BooleanField(default=False, verbose_name='Есть родительская категория'),
        ),
    ]
