# Generated by Django 4.2.7 on 2023-11-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_text', models.TextField(verbose_name='Коментарий')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='childComent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_text', models.TextField(verbose_name='Коментарий')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('fatherComdent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coments.coment')),
            ],
        ),
    ]
