# Generated by Django 4.2.7 on 2023-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0002_alter_coment_options_coment_filef_delete_childcoment'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileF', models.FileField(upload_to='', verbose_name='Файл')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.RemoveField(
            model_name='coment',
            name='fileF',
        ),
    ]
