# Generated by Django 4.2.7 on 2023-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0003_filecomment_remove_coment_filef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecomment',
            name='fileF',
        ),
        migrations.AddField(
            model_name='filecomment',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
