# Generated by Django 4.2.7 on 2023-11-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0004_remove_filecomment_filef_filecomment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя документа'),
            preserve_default=False,
        ),
    ]
