# Generated by Django 4.2.7 on 2023-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0008_rename_coment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(default=0, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='documentName',
            field=models.CharField(max_length=50, verbose_name='Имя фото'),
        ),
    ]
