# Generated by Django 4.2.7 on 2023-11-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0011_comment_id_страницы'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Id страницы',
        ),
        migrations.AddField(
            model_name='comment',
            name='idOfPage',
            field=models.IntegerField(default=0, verbose_name='Id страницы'),
            preserve_default=False,
        ),
    ]
