# Generated by Django 4.2.7 on 2023-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0013_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='adminNameComment',
            field=models.TextField(default=0, verbose_name='Имя объекта'),
            preserve_default=False,
        ),
    ]
