# Generated by Django 4.2.7 on 2023-12-31 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0017_alter_comment_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='idOfPage',
        ),
    ]
