version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8000:80

  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: web
    expose:
      - 8080
    volumes:
      - ./GES:/GES
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"

  

  # В контейнере два сервиса. nginx -  обратный прокси веб-сервер + сенрвер для unity. 
  # И веб 
