version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    depends_on:
      - frontend
    restart: always

    
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    image: backend
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_HOST=database
      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=pass

    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      - database

  frontend:
      container_name: frontend
      build: 
        context: .
        dockerfile: Dockerfile.frontend
      expose:
        - 3000
      depends_on:
        - backend

  database:
    container_name: database
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
