
FROM node:18.17.0-alpine


WORKDIR /app


COPY frontend/package*.json ./

RUN npm install
RUN npm install axios handy-svg react-svg react-router-dom styled-components vis-network


COPY frontend/ .

EXPOSE 3000

# Запускаем приложение
CMD ["npm", "start"]
