version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: web
    expose:
      - 8000
    volumes:
      - ./GES:/GES
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  unity:
    container_name: unity
    image: unity
    build: 
      context: .
      dockerfile: Dockerfile.unity
    expose:
      - 8080:80 
    ports:
      - 8080:80

    
  
  nginx:
    container_name: nginx 
    image: nginx
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
      - unity