FROM python:3.9-alpine3.16

COPY api/requirements.txt /app/requirements.txt 
COPY api /api

WORKDIR /api

EXPOSE 8000

RUN apk update && apk add --no-cache postgresql-client build-base postgresql-dev curl

RUN pip install -r /app/requirements.txt

RUN adduser --disabled-password fcg

RUN python manage.py makemigrations

USER fcg


