version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: web
    ports:
      - "8000:8000"
    volumes:
      - ./GES:/GES
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  webgl:
    container_name: unity
    image: unity
    build: 
      context: .
      dockerfile: Dockerfile.unity
    ports:
      - "8080:80"