# Generated by Django 4.2.15 on 2024-10-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfCatergory', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('countOfNestedWorld', models.IntegerField(default=0, verbose_name='Количество миров')),
                ('flagForInternalRecordings', models.BooleanField(default=False, verbose_name='Есть подкатегории')),
                ('flagForThePresenceOfAParent', models.BooleanField(default=False, verbose_name='Есть родительская категория')),
                ('internalPages', models.ManyToManyField(blank=True, related_name='related_pages', to='category.category')),
                ('parentPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pages', to='category.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
