# Generated by Django 4.2.16 on 2024-10-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_nameofcatergory_category_nameofcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parentPage',
            new_name='parentCategory',
        ),
    ]
