# Generated by Django 4.2.16 on 2024-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_parentcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='internalPages',
            new_name='childCategoies',
        ),
    ]
