# Generated by Django 4.2.7 on 2023-12-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nameOfPage',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('published', 'Опубликовано')], default=0, max_length=20, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
