# Generated by Django 4.2.7 on 2023-12-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_map_nameofpage'),
        ('PAGE', '0003_alter_page_nameofpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='map',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='map.map', verbose_name='Родительская категория'),
            preserve_default=False,
        ),
    ]
