# Generated by Django 4.2.7 on 2024-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0008_remove_page_id_категории'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='graphical_MMOs_TAG',
            field=models.CharField(choices=[('MMORPG', 'MMORPG'), ('MMOCCG', 'MMOCCG'), ('sandbox', 'sandbox'), ('dance', 'dance'), ('kids', 'kids'), ('teens', 'teens'), ('social', 'social'), ('musical', 'musical'), ('educational', 'educational'), ('deadserver', 'deadserver'), ('revived', 'revived by community')], default=0, max_length=20, verbose_name='ТЭГ graphical_MMOs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='text_based_MMOs_T',
            field=models.CharField(choices=[('MUD', 'Multi-User Dungeon'), ('MUD_OO', 'MUD Object Oriented'), ('MUSH', 'Multi-User Shared Hallucination'), ('MMORPG', 'MMORPG'), ('educational', 'educational'), ('social', 'social'), ('deadserver', 'deadserver')], default=1, max_length=20, verbose_name='ТЭГ text_based_MMOs'),
            preserve_default=False,
        ),
    ]
