# Generated by Django 4.2.13 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0009_page_graphical_mmos_tag_page_text_based_mmos_t'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница виртуального мира', 'verbose_name_plural': 'Страницы виртувльных миров'},
        ),
        migrations.AlterField(
            model_name='page',
            name='graphical_MMOs_TAG',
            field=models.CharField(blank=True, choices=[('MMORPG', 'MMORPG'), ('MMOCCG', 'MMOCCG'), ('sandbox', 'sandbox'), ('dance', 'dance'), ('kids', 'kids'), ('teens', 'teens'), ('social', 'social'), ('musical', 'musical'), ('educational', 'educational'), ('deadserver', 'deadserver'), ('revived', 'revived by community')], max_length=20, verbose_name='ТЭГ graphical_MMOs'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'На рассмотрении'), ('published', 'Опубликовано')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_based_MMOs_T',
            field=models.CharField(blank=True, choices=[('MUD', 'Multi-User Dungeon'), ('MUD_OO', 'MUD Object Oriented'), ('MUSH', 'Multi-User Shared Hallucination'), ('MMORPG', 'MMORPG'), ('educational', 'educational'), ('social', 'social'), ('deadserver', 'deadserver')], max_length=20, verbose_name='ТЭГ text_based_MMOs'),
        ),
    ]
