# Generated by Django 4.2.7 on 2023-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_map_id_страницы'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='nameOfPage',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя страницы'),
            preserve_default=False,
        ),
    ]
