# Generated by Django 4.2.7 on 2023-12-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_map_nameofpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Имя страницы', 'verbose_name_plural': 'Имена страниц'},
        ),
    ]
