# Generated by Django 4.2.7 on 2023-12-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_map_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
