# Generated by Django 4.2.7 on 2023-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_map_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('published', 'Опубликовано')], default=0, max_length=20, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
