# Generated by Django 4.2.7 on 2023-12-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_map_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='FlagForInternalRecordings',
            field=models.IntegerField(default=0, verbose_name='Флаг на наличие внутренних записей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='internal_pages',
            field=models.ManyToManyField(blank=True, related_name='related_pages', to='map.map'),
        ),
    ]
