# Generated by Django 4.2.7 on 2023-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_map_flagforinternalrecordings_map_internal_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='FlagForInternalRecordings',
            field=models.IntegerField(default=0, verbose_name='Флаг на наличие внутренних записей'),
        ),
    ]
