# Generated by Django 4.2.7 on 2023-12-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_remove_map_nameofpage_remove_map_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='nameOfPage',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя категории'),
            preserve_default=False,
        ),
    ]
