# Generated by Django 4.2.7 on 2024-03-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_alter_map_flagforthepresenceofaparent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pages', to='map.map'),
        ),
    ]
