# Generated by Django 4.2.7 on 2023-12-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0002_page_nameofpage_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='nameOfPage',
            field=models.CharField(max_length=50, verbose_name='Имя страницы'),
        ),
    ]
