# Generated by Django 4.2.7 on 2023-12-31 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0004_page_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='map',
        ),
    ]
