# Generated by Django 4.2.7 on 2023-12-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0006_page_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Id категории',
            field=models.IntegerField(default=0, verbose_name='id'),
            preserve_default=False,
        ),
    ]
