# Generated by Django 4.2.15 on 2024-08-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0010_alter_page_options_alter_page_graphical_mmos_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Коментарий')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('document', models.FileField(upload_to='documents/')),
                ('documentName', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('username', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('adminNameComment', models.TextField(verbose_name='Имя комментария')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAGE.page', verbose_name='Страница на которой оставили комментарий')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
