# Generated by Django 4.2.15 on 2024-08-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница виртуального мира', 'verbose_name_plural': 'Страницы виртуальных миров'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAGE.page', verbose_name='Страница, на которой оставили комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
