# Generated by Django 4.2.15 on 2024-10-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfPage', models.CharField(max_length=50, verbose_name='Имя страницы')),
                ('reviewStatus', models.CharField(blank=True, choices=[('pending', 'На рассмотрении'), ('published', 'Опубликовано')], max_length=20, verbose_name='Статус')),
                ('tagTextBasedMMOs', models.CharField(blank=True, choices=[('MUD', 'Multi-User Dungeon'), ('MUD_OO', 'MUD Object Oriented'), ('MUSH', 'Multi-User Shared Hallucination'), ('MMORPG', 'MMORPG'), ('educational', 'educational'), ('social', 'social'), ('deadserver', 'deadserver')], max_length=20, verbose_name='ТЭГ text_based_MMOs')),
                ('tagGraphicalMMOs', models.CharField(blank=True, choices=[('MMORPG', 'MMORPG'), ('MMOCCG', 'MMOCCG'), ('sandbox', 'sandbox'), ('dance', 'dance'), ('kids', 'kids'), ('teens', 'teens'), ('social', 'social'), ('musical', 'musical'), ('educational', 'educational'), ('deadserver', 'deadserver'), ('revived', 'revived by community')], max_length=20, verbose_name='ТЭГ graphical_MMOs')),
                ('parentCoategoryKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Страница виртуального мира',
                'verbose_name_plural': 'Страницы виртуальных миров',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(verbose_name='Комментарий')),
                ('publishedDate', models.DateTimeField(verbose_name='Дата публикации')),
                ('username', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('ParentPageKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Страница, на которой оставили комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
