# Generated by Django 4.2.16 on 2024-10-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='parentCoategoryKey',
            new_name='parentCategoryKey',
        ),
    ]
