# Generated by Django 4.2.16 on 2024-10-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_parentcoategorykey_page_parentcategorykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parentCategoryKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='page.page', verbose_name='Родительская категория'),
        ),
    ]
