# Generated by Django 4.2.16 on 2024-10-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_parentcategory'),
        ('page', '0003_alter_page_parentcategorykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parentCategoryKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Родительская категория'),
            preserve_default=False,
        ),
    ]
