name: Deploy to Server

on:
  push:
    branches:
      - master  # Запускать пайплайн при пуше в ветку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses:  webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 89.19.216.56 >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      run: |
        scp -r ./* root@89.19.216.56:

    - name: Run docker-compose
      run: |
         ssh root@89.19.216.56 "
           docker-compose down && docker-compose up --build -d

        "
