# Generated by Django 4.2.7 on 2023-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0005_filecomment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecomment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
