# Generated by Django 4.2.7 on 2023-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0010_remove_comment_photo_alter_comment_documentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Id страницы',
            field=models.IntegerField(default=0, verbose_name='idOfPage'),
            preserve_default=False,
        ),
    ]
