# Generated by Django 4.2.7 on 2023-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0012_remove_comment_id_страницы_comment_idofpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=0, max_length=25, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
