# Generated by Django 4.2.7 on 2023-11-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0014_comment_adminnamecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
