# Generated by Django 4.2.7 on 2023-12-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_map_status'),
        ('coments', '0014_comment_adminnamecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='idOfPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.map'),
        ),
    ]
