# Generated by Django 4.2.7 on 2023-12-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_map_status'),
        ('coments', '0015_alter_comment_idofpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='map.map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='idOfPage',
            field=models.IntegerField(verbose_name='Id страницы'),
        ),
    ]
