# Generated by Django 4.2.7 on 2023-12-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAGE', '0006_page_map'),
        ('coments', '0016_comment_cat_alter_comment_idofpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAGE.page', verbose_name='Страница на которой оставили комментарий'),
        ),
    ]
