# Generated by Django 4.2.7 on 2023-12-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0018_remove_comment_idofpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='adminNameComment',
            field=models.TextField(verbose_name='Имя комментария'),
        ),
    ]
